(function bootstrapSiteCopy(windowObject) {
  windowObject.EnigmaticaSiteCopy = {
    common: {
      brandName: "ENIGMATICA",
      homeBrandSubtitle: "Decoding playground",
      playBrandSubtitle: "Interactive mode",
      resetProgress: "Reset Progress",
      play: "Play",
      continue: "Continue",
      home: "Home",
      notesLink: "Open chapter notes",
      progressEmpty: "0 / 0 solved",
      chapterCountEmpty: "0 total",
      total: "total",
      solved: "solved",
      puzzles: "puzzles",
    },
    home: {
      volumeLabel: "Volume 01",
      heroTitle: "Decode before the clock runs out.",
      heroCopy:
        "Enigmatica inspired decoding challenges. Each chapter introduces a new mechanic, then folds it into the larger game.",
      heroKicker: "12 HOURS LEFT TO LIVE",
      heroCaption: "Chapter 1 playable build",
      startInteractive: "Start Interactive Mode",
      resumeInteractive: "Resume Interactive Mode",
      continueChapter: "Continue Chapter",
      aboutEyebrow: "What It Is",
      aboutTitle: "Chapter by chapter, mechanic by mechanic.",
      aboutCopy:
        "This project follows a seinen manga by Kanji Shiba.",
      howEyebrow: "How It Works",
      featureCards: [
        {
          title: "Read the clue",
          body: "Start from the manga image, cipher strip, board, or coded message.",
        },
        {
          title: "Find the rule",
          body: "Use the chapter mechanic to turn the clue into a meaningful answer.",
        },
        {
          title: "Advance the chapter",
          body: "Play one puzzle at a time and unlock the next step in sequence.",
        },
      ],
      chaptersEyebrow: "Chapters",
      openChapter: "Open interactive chapter",
      continueChapterCard: "Continue chapter",
      lockedChapter: "Complete previous chapter to unlock",
    },
    play: {
      modeEyebrow: "Interactive Mode",
      flowEyebrow: "Puzzle Flow",
      flowDefault: "Sequential unlocks",
      instructionEyebrow: "Instruction",
      answerLabel: "Your answer",
      answerPlaceholder: "Type your guess",
      answerPlaceholderSolved: "Already solved. You can still replay it.",
      submit: "Submit",
      showHint: "Show Hint",
      hideHint: "Hide Hint",
      continue: "Continue",
      puzzleFallback: "Puzzle",
      loading: "Loading...",
      mechanicFallback: "Mechanic",
      stateSolved: "Solved",
      stateOpen: "Open",
      stateLocked: "Locked",
      clueLetterStrip: "Letter Strip",
      cluePositions: "Positions",
      clueBoardReference: "Board Reference",
      clueSourceClue: "Source Clue",
      clueAlphabet: "Alphabet",
      clueInverseMatrix: "Inverse Matrix",
      clueCiphertextBlocks: "Ciphertext Blocks",
      cluePolybiusBoard: "Polybius Board",
      cluePlayableCoordinates: "Playable Coordinates",
      sourceSnapshot: "Source Snapshot",
      mechanicSnapshot: "Mechanic Reference",
      ruleSnapshot: "Rule Reference",
    },
    interface: {
      dataLoadError:
        "The chapter data could not be loaded. Run the export step and serve the repo over HTTP.",
      confirmReset: "Reset local chapter progress in this browser?",
      typeAnswerFirst: "Type an answer first.",
      noHint: "No hint is available for this puzzle yet.",
      correctUnlock: "Correct. The next puzzle is unlocked.",
      incorrect: "Not quite yet. Try again or reveal the hint.",
      chapterClearReplay: "Chapter clear. Return home or replay any puzzle here.",
      chapterClearSoon: "Chapter clear. More chapters soon.",
      progressReset: "Progress reset.",
      solvedReplay: "Solved. You can move on or replay it here.",
      ready: "Ready when you are.",
    },
  };
})(window);
